### PR TITLE
Memory Leak Fixes: Release CFArrayRef and App Instances 

### PR DESCRIPTION
**Pull request by chevonc**
Noticed that memory grew uncontained while using our application. I believe the core issue is that we don't release retained refs to CF (CoreFoundation) objects. 

Please, let me know if you have any feedback/concerns. I'd love to get the merges asap, so we can use the updated package.

https://github.com/sentialx/node-window-manager/issues/42

### CODE REVIEW

**Comment by sentialx** [comment]
Thanks for your great PR! Looks good to me.

**Comment by chevonc** [comment]
@sentialx quick question here about consuming the updated package - it looks like the latest release on npm is about ~4 months ago, though there have been merges to master. Any chance you could publish a new version with these changes soon?

**Comment by sentialx** [comment]
@chevonc Released in 2.1.1

**Comment by chevonc** [comment]
Thanks @sentialx - sorry about this, but looks like there's an issue with the latest release on macosx because of a small regression I caused. Submitted #44 if we can get that guy pushed out

**Pull request merged**
